-- SQL to populate phone_case_styles from photos
-- Run this in Supabase SQL Editor

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-15-solid-color', 'iphone-15', 'Solid Color', '/images/Phone Case Style/Iphone 15/Solid Color/Green.jpeg', 1, '[{"label":"Green","type":"photo","value":"/images/Phone Case Style/Iphone 15/Solid Color/Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 15/Solid Color/Pink.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-15-solid-color-frame', 'iphone-15', 'Solid Color Frame', '/images/Phone Case Style/Iphone 15/Solid Color Ferame/Black.jpeg', 2, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 15/Solid Color Ferame/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 15/Solid Color Ferame/Blue.jpeg"},{"label":"Cyan","type":"photo","value":"/images/Phone Case Style/Iphone 15/Solid Color Ferame/Cyan.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 15/Solid Color Ferame/Purple.jpeg"},{"label":"Transparent","type":"photo","value":"/images/Phone Case Style/Iphone 15/Solid Color Ferame/Transparent.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 15/Solid Color Ferame/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-15-wave-transparent', 'iphone-15', 'Wave Transparent', '/images/Phone Case Style/Iphone 15/Wave Transparent/Black.jpeg', 3, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 15/Wave Transparent/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 15/Wave Transparent/Blue.jpeg"},{"label":"Light Yellow","type":"photo","value":"/images/Phone Case Style/Iphone 15/Wave Transparent/Light Yellow.jpeg"},{"label":"Mint Green","type":"photo","value":"/images/Phone Case Style/Iphone 15/Wave Transparent/Mint Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 15/Wave Transparent/Pink.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 15/Wave Transparent/Purple.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 15/Wave Transparent/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-15-plus-solid-color', 'iphone-15-plus', 'Solid Color', '/images/Phone Case Style/Iphone 15plus/Solid Color/Green.jpeg', 4, '[{"label":"Green","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Solid Color/Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Solid Color/Pink.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-15-plus-solid-color-frame', 'iphone-15-plus', 'Solid Color Frame', '/images/Phone Case Style/Iphone 15plus/Solid Color Ferame/Black.jpeg', 5, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Solid Color Ferame/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Solid Color Ferame/Blue.jpeg"},{"label":"Cyan","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Solid Color Ferame/Cyan.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Solid Color Ferame/Purple.jpeg"},{"label":"Transparent","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Solid Color Ferame/Transparent.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Solid Color Ferame/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-15-plus-wave-transparent', 'iphone-15-plus', 'Wave Transparent', '/images/Phone Case Style/Iphone 15plus/Wave Transparent/Black.jpeg', 6, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Wave Transparent/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Wave Transparent/Blue.jpeg"},{"label":"Light Yellow","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Wave Transparent/Light Yellow.jpeg"},{"label":"Mint Green","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Wave Transparent/Mint Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Wave Transparent/Pink.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Wave Transparent/Purple.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 15plus/Wave Transparent/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-15-pro-solid-color', 'iphone-15-pro', 'Solid Color', '/images/Phone Case Style/Iphone 15pro/Solid Color/Green.jpeg', 7, '[{"label":"Green","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Solid Color/Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Solid Color/Pink.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-15-pro-solid-color-frame', 'iphone-15-pro', 'Solid Color Frame', '/images/Phone Case Style/Iphone 15pro/Solid Color Ferame/Black.jpeg', 8, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Solid Color Ferame/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Solid Color Ferame/Blue.jpeg"},{"label":"Cyan","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Solid Color Ferame/Cyan.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Solid Color Ferame/Purple.jpeg"},{"label":"Transparent","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Solid Color Ferame/Transparent.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Solid Color Ferame/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-15-pro-wave-transparent', 'iphone-15-pro', 'Wave Transparent', '/images/Phone Case Style/Iphone 15pro/Wave Transparent/Black.jpeg', 9, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Wave Transparent/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Wave Transparent/Blue.jpeg"},{"label":"Light Yellow","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Wave Transparent/Light Yellow.jpeg"},{"label":"Mint Green","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Wave Transparent/Mint Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Wave Transparent/Pink.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Wave Transparent/Purple.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 15pro/Wave Transparent/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-15-pro-max-solid-color', 'iphone-15-pro-max', 'Solid Color', '/images/Phone Case Style/Iphone 15 promax/Solid Color/Green.jpeg', 10, '[{"label":"Green","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Solid Color/Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Solid Color/Pink.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-15-pro-max-solid-color-frame', 'iphone-15-pro-max', 'Solid Color Frame', '/images/Phone Case Style/Iphone 15 promax/Solid Color Ferame/Black.jpeg', 11, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Solid Color Ferame/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Solid Color Ferame/Blue.jpeg"},{"label":"Cyan","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Solid Color Ferame/Cyan.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Solid Color Ferame/Purple.jpeg"},{"label":"Transparent","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Solid Color Ferame/Transparent.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Solid Color Ferame/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-15-pro-max-wave-transparent', 'iphone-15-pro-max', 'Wave Transparent', '/images/Phone Case Style/Iphone 15 promax/Wave Transparent/Black.jpeg', 12, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Wave Transparent/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Wave Transparent/Blue.jpeg"},{"label":"Light Yellow","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Wave Transparent/Light Yellow.jpeg"},{"label":"Mint Green","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Wave Transparent/Mint Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Wave Transparent/Pink.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Wave Transparent/Purple.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 15 promax/Wave Transparent/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-16-solid-color-frame', 'iphone-16', 'Solid Color Frame', '/images/Phone Case Style/Iphone 16/Solid Color Frame/Black.jpeg', 13, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 16/Solid Color Frame/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 16/Solid Color Frame/Blue.jpeg"},{"label":"Cyan","type":"photo","value":"/images/Phone Case Style/Iphone 16/Solid Color Frame/Cyan.jpeg"},{"label":"Green","type":"photo","value":"/images/Phone Case Style/Iphone 16/Solid Color Frame/Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 16/Solid Color Frame/Pink.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 16/Solid Color Frame/Purple.jpeg"},{"label":"Transparent","type":"photo","value":"/images/Phone Case Style/Iphone 16/Solid Color Frame/Transparent.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 16/Solid Color Frame/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-16-wave-transparent', 'iphone-16', 'Wave Transparent', '/images/Phone Case Style/Iphone 16/Wave Transparent/Black.jpeg', 14, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 16/Wave Transparent/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 16/Wave Transparent/Blue.jpeg"},{"label":"Light Yellow","type":"photo","value":"/images/Phone Case Style/Iphone 16/Wave Transparent/Light Yellow.jpeg"},{"label":"Mint Green","type":"photo","value":"/images/Phone Case Style/Iphone 16/Wave Transparent/Mint Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 16/Wave Transparent/Pink.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 16/Wave Transparent/Purple.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 16/Wave Transparent/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-16-plus-solid-color', 'iphone-16-plus', 'Solid Color', '/images/Phone Case Style/Iphone 16plus/Solid Color/Green.jpeg', 15, '[{"label":"Green","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Solid Color/Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Solid Color/Pink.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-16-plus-solid-color-frame', 'iphone-16-plus', 'Solid Color Frame', '/images/Phone Case Style/Iphone 16plus/Solid Color Ferame/Black.jpeg', 16, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Solid Color Ferame/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Solid Color Ferame/Blue.jpeg"},{"label":"Cyan","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Solid Color Ferame/Cyan.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Solid Color Ferame/Purple.jpeg"},{"label":"Transparent","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Solid Color Ferame/Transparent.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Solid Color Ferame/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-16-plus-wave-transparent', 'iphone-16-plus', 'Wave Transparent', '/images/Phone Case Style/Iphone 16plus/Wave Transparent/Black.jpeg', 17, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Wave Transparent/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Wave Transparent/Blue.jpeg"},{"label":"Light Yellow","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Wave Transparent/Light Yellow.jpeg"},{"label":"Mint Green","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Wave Transparent/Mint Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Wave Transparent/Pink.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Wave Transparent/Purple.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 16plus/Wave Transparent/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-16-pro-solid-color', 'iphone-16-pro', 'Solid Color', '/images/Phone Case Style/Iphone 16pro/Solid Color/Green.jpeg', 18, '[{"label":"Green","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Solid Color/Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Solid Color/Pink.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-16-pro-solid-color-frame', 'iphone-16-pro', 'Solid Color Frame', '/images/Phone Case Style/Iphone 16pro/Solid Color Ferame/Black.jpeg', 19, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Solid Color Ferame/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Solid Color Ferame/Blue.jpeg"},{"label":"Cyan","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Solid Color Ferame/Cyan.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Solid Color Ferame/Purple.jpeg"},{"label":"Transparent","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Solid Color Ferame/Transparent.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Solid Color Ferame/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-16-pro-wave-transparent', 'iphone-16-pro', 'Wave Transparent', '/images/Phone Case Style/Iphone 16pro/Wave Transparent/Black.jpeg', 20, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Wave Transparent/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Wave Transparent/Blue.jpeg"},{"label":"Light Yellow","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Wave Transparent/Light Yellow.jpeg"},{"label":"Mint Green","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Wave Transparent/Mint Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Wave Transparent/Pink.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Wave Transparent/Purple.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 16pro/Wave Transparent/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-16-pro-max-solid-color', 'iphone-16-pro-max', 'Solid Color', '/images/Phone Case Style/Iphone 16 Promax/Solid Color/Green.jpeg', 21, '[{"label":"Green","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Solid Color/Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Solid Color/Pink.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-16-pro-max-solid-color-frame', 'iphone-16-pro-max', 'Solid Color Frame', '/images/Phone Case Style/Iphone 16 Promax/Solid Color Ferame/Black.jpeg', 22, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Solid Color Ferame/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Solid Color Ferame/Blue.jpeg"},{"label":"Cyan","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Solid Color Ferame/Cyan.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Solid Color Ferame/Purple.jpeg"},{"label":"Transparent","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Solid Color Ferame/Transparent.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Solid Color Ferame/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-16-pro-max-wave-transparent', 'iphone-16-pro-max', 'Wave Transparent', '/images/Phone Case Style/Iphone 16 Promax/Wave Transparent/Black.jpeg', 23, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Wave Transparent/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Wave Transparent/Blue.jpeg"},{"label":"Light Yellow","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Wave Transparent/Light Yellow.jpeg"},{"label":"Mint Green","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Wave Transparent/Mint Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Wave Transparent/Pink.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Wave Transparent/Purple.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 16 Promax/Wave Transparent/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-17-solid-color-frame', 'iphone-17', 'Solid Color Frame', '/images/Phone Case Style/Iphone 17/Solid Color Frame/Black.jpeg', 24, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 17/Solid Color Frame/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 17/Solid Color Frame/Blue.jpeg"},{"label":"Cyan","type":"photo","value":"/images/Phone Case Style/Iphone 17/Solid Color Frame/Cyan.jpeg"},{"label":"Green","type":"photo","value":"/images/Phone Case Style/Iphone 17/Solid Color Frame/Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 17/Solid Color Frame/Pink.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 17/Solid Color Frame/Purple.jpeg"},{"label":"Transparent","type":"photo","value":"/images/Phone Case Style/Iphone 17/Solid Color Frame/Transparent.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 17/Solid Color Frame/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-17-pro-solid-color-frame', 'iphone-17-pro', 'Solid Color Frame', '/images/Phone Case Style/Iphone 17pro/Solid Color Frame/Black.jpeg', 25, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 17pro/Solid Color Frame/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 17pro/Solid Color Frame/Blue.jpeg"},{"label":"Cyan","type":"photo","value":"/images/Phone Case Style/Iphone 17pro/Solid Color Frame/Cyan.jpeg"},{"label":"Green","type":"photo","value":"/images/Phone Case Style/Iphone 17pro/Solid Color Frame/Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 17pro/Solid Color Frame/Pink.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 17pro/Solid Color Frame/Purple.jpeg"},{"label":"Transparent","type":"photo","value":"/images/Phone Case Style/Iphone 17pro/Solid Color Frame/Transparent.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 17pro/Solid Color Frame/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO phone_case_styles (id, model_id, name, image_url, display_order, colors) VALUES
  ('iphone-17-pro-max-solid-color-frame', 'iphone-17-pro-max', 'Solid Color Frame', '/images/Phone Case Style/Iphone 17promax/Solid Color Frame/Black.jpeg', 26, '[{"label":"Black","type":"photo","value":"/images/Phone Case Style/Iphone 17promax/Solid Color Frame/Black.jpeg"},{"label":"Blue","type":"photo","value":"/images/Phone Case Style/Iphone 17promax/Solid Color Frame/Blue.jpeg"},{"label":"Cyan","type":"photo","value":"/images/Phone Case Style/Iphone 17promax/Solid Color Frame/Cyan.jpeg"},{"label":"Green","type":"photo","value":"/images/Phone Case Style/Iphone 17promax/Solid Color Frame/Green.jpeg"},{"label":"Pink","type":"photo","value":"/images/Phone Case Style/Iphone 17promax/Solid Color Frame/Pink.jpeg"},{"label":"Purple","type":"photo","value":"/images/Phone Case Style/Iphone 17promax/Solid Color Frame/Purple.jpeg"},{"label":"Transparent","type":"photo","value":"/images/Phone Case Style/Iphone 17promax/Solid Color Frame/Transparent.jpeg"},{"label":"White","type":"photo","value":"/images/Phone Case Style/Iphone 17promax/Solid Color Frame/White.jpeg"}]'::jsonb)
ON CONFLICT (id) DO NOTHING;
